export const headers = {
  accept: "*/*",
  "accept-language": "vi-VN,vi;q=0.9,fr-FR;q=0.8,fr;q=0.7,en-US;q=0.6,en;q=0.5",
  "content-length": "0",
  "content-type": "application/x-www-form-urlencoded",
  origin: "https://www.tiktok.com",
  priority: "u=1, i",
  referer: "https://www.google.com",
  "sec-ch-ua": '"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"',
  "sec-ch-ua-mobile": "?0",
  "sec-ch-ua-platform": '"Windows"',
  "sec-fetch-dest": "empty",
  "sec-fetch-mode": "cors",
  "sec-fetch-site": "same-origin",
  "tt-csrf-token": "VtZhDuGD-STsUQy43Dj6-oDjZOIfZyetcoxY",
  "tt-ticket-guard-client-data": "eyJ0c19zaWduIjoidHMuMS4wOGI1ZWQ2MmNmY2QwMDM2OWRlY2MwMWU2YzNmZjczMTE5OWY4MGQwODg1M2ExZmJjZjdmNTA3NTM4YWI5Y2M1MGU3MGI0YmRhODJjMTM4MzZlNWNmYTE4Mzk0ZDcwMjQwZjhhZjE2MzFmMTY1YWU5NjAxMjJlZWZmZDQ1MzNkZCIsInJlcV9jb250ZW50IjoidGlja2V0LHBhdGgsdGltZXN0YW1wIiwicmVxX3NpZ24iOiJNRVlDSVFEL0twd2cwUVJ1ZExXMnB1NEUwNWx2Q1pIcFcvcWpUT3h4NXJqT3UxRk5nQUloQU9NendVMkczOWppN1k1MzJUaHpTME9mcFc3RWkxam1ncXo1c0xxNU9Bc3EiLCJ0aW1lc3RhbXAiOjE3NjM5NjY4MDR9",
  "tt-ticket-guard-iteration-version": "0",
  "tt-ticket-guard-public-key": "BHyNwZ32A59NI0M6aPbA6qddpq/ex+b07SQEEP3CqC4Lr2xElba16e8AqJ3fYvyC2Xz1I7VbN5B2Sg6j85b5mQQ=",
  "tt-ticket-guard-version": "2",
  "tt-ticket-guard-web-version": "1",
  "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36",
};

export function get_payload_info({ device_id, odinId="" }) {
  return {
    "WebIdLastTime": "1763632686",
    "aid": "1988",
    "app_language": "vi-VN",
    "app_name": "tiktok_web",
    "browser_language": "vi-VN",
    "browser_name": "Mozilla",
    "browser_online": "true",
    "browser_platform": "Win32",
    "browser_version": "5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36",
    "channel": "tiktok_web",
    "cookie_enabled": "true",
    "data_collection_enabled": "true",
    "device_id": device_id,
    "device_platform": "web_pc",
    "focus_state": "true",
    "from_page": "setting",
    "history_len": "9",
    "is_fullscreen": "false",
    "is_page_visible": "true",
    "odinId": odinId,
    "os": "windows",
    "priority_region": "VN",
    "referer": "",
    "region": "VN",
    "screen_height": "1080",
    "screen_width": "1920",
    "tz_name": "Asia/Bangkok",
    "user_is_login": "true",
    "webcast_language": "vi-VN"
  };
}

export function get_payload_like({
  aweme_id,
  odinId,
  device_id,
  verifyFp="",
  msToken,
}) {
  return {
    "WebIdLastTime": "1763632686",
    "aid": "1988",
    "app_language": "vi-VN",
    "app_name": "tiktok_web",
    "aweme_id": aweme_id,
    "browser_language": "vi-VN",
    "browser_name": "Mozilla",
    "browser_online": "true",
    "browser_platform": "Win32",
    "browser_version": "5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36",
    "channel": "tiktok_web",
    'cookie_enabled': "true",
    "data_collection_enabled": "true",
    "device_id": device_id,
    "device_platform": "web_pc",
    "focus_state": "false",
    "from_page": "video",
    "history_len": "15",
    "is_fullscreen": "false",
    "is_page_visible": "true",
    "odinId": odinId,
    "os": "windows",
    "priority_region": "VN",
    "referer": "",
    "region": "VN",
    "root_referer": "https://www.google.com/",
    "screen_height": "1440",
    "screen_width": "2560",
    "type": "1",
    'tz_name': "Asia/Bangkok",
    'user_is_login': "true",
    'verifyFp': verifyFp,
    'webcast_language': "vi-VN",
    'msToken': msToken,
  };
}
